@base_address = http://localhost:5168/api/people

GET {{base_address}}

###
GET {{base_address}}/3

###
POST {{base_address}}
Content-Type: application/json

{
  "firstName": "Jack",
  "lastName": "Sparrow"
}

###
POST {{base_address}}
Content-Type: application/json

{
  "id": 3,
  "firstName": "James",
  "lastName": "Gunn"
}

###
DELETE {{base_address}}/3